### PR TITLE
Feat/set gossip arc clamping

### PR DESCRIPTION
**Pull request by mattyg**
- Adds a cli option to clamp gossip arc to "full" or "empty", defaults to "none".
- run clippy fix

### CODE REVIEW

**Comment by Connoropolous** [comment]
looking good. what's your use case for this?

**Comment by mattyg** [comment]
> looking good. what's your use case for this?

running an always-online peer from a server with a full arc for additional dht resilience

**Comment by Connoropolous** [comment]
makes sense, yeah!

**Comment by Connoropolous** [comment]
would you set it to "full" then?

**Comment by mattyg** [comment]
> would you set it to "full" then?

yep exactly

**Comment by Connoropolous** [comment]
so “none” means utilize the default, which is for it to dynamic?

**Comment by mattyg** [comment]
> so “none” means utilize the default, which is for it to dynamic?

yep -- here's the docs on it: https://github.com/holochain/holochain/blob/7ae110bf790cc8cd2b1aa0e9161a018f5f81955f/crates/kitsune_p2p/types/src/config.rs#L156

**Review by Connoropolous — APPROVED** [review]

**Pull request merged**
