### PR TITLE
upgrade holochain version

### PR DESCRIPTION
**Pull request by kbonnici**

### CODE REVIEW

**Comment by kbonnici** [comment]
may need to change links in the readme, but im not sure what the urls should be. i tried doing `docs.rs/hdk/0.3.0/hdk/index.html` but that didnt seem to work

**Comment by Connoropolous** [comment]
re. docs, this build of the docs seems to have failed. 
https://docs.rs/crate/holochain/0.3.0-beta-dev.3

We could either comment out those lines in the readme for this release, or put in the link but to a broken page

**Comment by Connoropolous** [comment]
I prefer commenting out than a bad link I think

**Comment by Connoropolous** [comment]
or, just remove the link, but not the text

**Comment by Connoropolous** [comment]
looks good overall

**Pull request merged**
