### PR TITLE
feat: read lair password from env file key LAIR_PASSWORD

### PR DESCRIPTION
**Pull request by mattyg**
Adds an option to specify an env file, and read the lair password from that file

### CODE REVIEW

**Comment by Connoropolous** [comment]
nice. 
are you using 0.1 stream of this, or 0.2 stream, by the way?

**Comment by mattyg** [comment]
I've been using 0.2, although now aiming to get all the functionality integrated into the hc sandbox (seems like its there, just quirky UX).

**Comment by Connoropolous** [comment]
doesnt the name "sandbox" kind of imply non production environments?

**Comment by mattyg** [comment]
> doesnt the name "sandbox" kind of imply non production environments?

:laughing: I literally asked the same thing during a recent office hours. I think it needs a name change (and also splitting the zome call functions out into a "client" command). But yeah you can create conductor + lair configs for a production environment and then run it (as long as you work around some bugs and quirks).

**Pull request merged**
